### ISSUE TITLE
请问不能登录网页版微信的号是不是不能用本项目？

### ISSUE THREAD

**Issue by Marchccc** [hmllsnow/escape-wechat#6]
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/708e468c-08a2-47bd-917b-b82e7421e1f7">

**Comment by Marchccc** [comment]
还有个问题，请问扫码登录之后，手机是不是不能退出登录？

**Comment by hmllsnow** [comment]
应该不能退出手机微信

**Comment by hmllsnow** [comment]
我的微信也不能登录网页版微信，但是可以登录这个。如果这个不能登录，需要把微信实名认证，并绑定银行卡

**Comment by Marchccc** [comment]
登录之后，点击控制区重启才有回复，不知道说什么原因，如果能开个log就好了

**Comment by Marchccc** [comment]
@hmllsnow 你好，我群消息一直没成功不知道为什么，配置：
<img width="1612" alt="image" src="https://github.com/user-attachments/assets/c00d39ed-f5f1-428b-a79e-d2eb53c09d7b">

**Comment by hmllsnow** [comment]
群消息之前有bug，现在修复了。更新一下docker镜像即可

**Comment by Marchccc** [comment]
> 应该不能退出手机微信

是的

**Comment by Marchccc** [comment]
> 群消息之前有bug，现在修复了。更新一下docker镜像即可

谢谢，现在可以了～！：）

**Comment by Marchccc** [comment]
已解决
